version: "3"
services:
    hackpoints:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                GIT_COMMIT: ${GIT_COMMIT}
        ports:
            - 3000:3000
        networks:
            - hackpoints
        volumes:
            # This is go modules cache, without it you will have to
            # re-download all dependencies after restarting container
            - modules:/go/pkg/mod/cache

networks:
    hackpoints:
        external: false

volumes:
    modules:
        driver: local
